# Generated by Django 2.2.13 on 2020-07-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200712_0155'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagory',
            new_name='Category',
        ),
        migrations.AlterField(
            model_name='designerprofile',
            name='avatar',
            field=models.ImageField(default='avator.png', null=True, upload_to='desginer_avatar'),
        ),
    ]
