# Generated by Django 2.2.13 on 2020-07-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200712_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdismember',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='mdismember',
            name='member_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='mdismember',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='mdismember',
            index_together=set(),
        ),
    ]
