# Generated by Django 2.2.13 on 2020-07-12 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200712_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalart',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digital_art_category', to='api.Category'),
        ),
        migrations.AlterField(
            model_name='order',
            name='digital_art',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_digital_art', to='api.DigitalArt'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_member',
            field=models.BooleanField(default=False),
        ),
    ]
