# Generated by Django 2.2.13 on 2020-07-12 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200712_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price_in_all',
        ),
    ]
