# Generated by Django 2.2.13 on 2020-07-12 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_order_price_in_all'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdigitalart',
            name='title',
        ),
        migrations.AlterField(
            model_name='orderdigitalart',
            name='digital_art',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ODA_digital_art', to='api.DigitalArt'),
        ),
    ]
