# Generated by Django 2.2.13 on 2020-07-12 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200712_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdigitalart',
            name='download_url',
        ),
        migrations.RemoveField(
            model_name='orderdigitalart',
            name='price',
        ),
    ]
