# Generated by Django 2.2.13 on 2020-07-18 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_user_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='display_name',
        ),
    ]
